In [3]:
a=10
b=a
print(a)
print(b)

10
10


In [4]:
a=20
print(a)
print(b)

20
10


In [5]:
b=50
print(a)
print(b)

20
50


In [38]:
import numpy as np

# Shallow copy

Change in SUB ELEMENTS of MUTABLE objects

In [7]:
a = np.array([1,2,3,4])
b = a  #Shallow Copy
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [13]:
a[2] = 55
print(a)
print(b)

[ 1  2 55 75]
[ 1  2 55 75]


In [10]:
b[3] = 75
print(a)
print(b)

[ 1  2 55 75]
[ 1  2 55 75]


Change in whole mutable objects  

In [44]:
c = np.array([1,2,3,4])
d = c  #Shallow Copy
print(c)
print(d)

[1 2 3 4]
[1 2 3 4]


In [45]:
c = [11, 22, 33, 44, 55]
print(c)
print(d)

[11, 22, 33, 44, 55]
[1 2 3 4]


In [46]:
d = [100, 200, 300, 400]
print(c)
print(d)

[11, 22, 33, 44, 55]
[100, 200, 300, 400]


# Deep copy

In [14]:
a = np.array([1,2,3,4])
b = a.copy() #Deep Copy
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [15]:
a[2] = 55
print(a)
print(b)

[ 1  2 55  4]
[1 2 3 4]


In [16]:
b[3] = 75
print(a)
print(b)

[ 1  2 55  4]
[ 1  2  3 75]


# == Versus is

In [1]:
lst1 = ['CT1', 'CT2', 'CT3', 'CT4']
lst2 = ['CT1', 'CT2', 'CT3', 'CT4']

print(lst1 == lst2) #check values
print(lst1 is lst2) #check memory location

True
False


In [3]:
lst1[0] = 'KKK'
lst2[3] = 'ZZZ'

print(lst1)
print(lst2)

print(lst1 == lst2)
print(lst1 is lst2)

['KKK', 'CT2', 'CT3', 'CT4']
['CT1', 'CT2', 'CT3', 'ZZZ']
False
False


# ---------------------------------------

In [5]:
lstA = ['CT1', 'CT2', 'CT3', 'CT4']
lstB = lstA

print(lstA)
print(lstB)

print(lstA == lstB)
print(lstA is lstB)

['CT1', 'CT2', 'CT3', 'CT4']
['CT1', 'CT2', 'CT3', 'CT4']
True
True


In [7]:
lstA[0] = 'AAA'
lstB[3] = 'BBB'

print(lstA)
print(lstB)

print(lstA == lstB)
print(lstA is lstB)

['AAA', 'CT2', 'CT3', 'BBB']
['AAA', 'CT2', 'CT3', 'BBB']
True
True


# -------------------------------

In [8]:
a = 10
b = 10

print(a == b)
print(a is b)

True
True


In [14]:
b = 40

print(a)
print(b)

print(a == b)
print(a is b)

80
40
False
False


In [15]:
a = 80

print(a)
print(b)
        
print(a == b)
print(a is b)

80
40
False
False


In [ ]:
# ---------------------------------------

In [11]:
c = 10
d = c

print(c == d)
print(c is d)

True
True


In [16]:
d = 40

print(c)
print(d)

print(c == d)
print(c is d)

80
40
False
False


In [17]:
c = 80

print(c)
print(d)

print(c == d)
print(c is d)

80
40
False
False


# ----------------------------------------

In [21]:
str1 = 'chetan'
str2 = 'chetan'

print(str1 == str2)
print(str1 is str2)

True
True


In [22]:
str1 = 'kishan'

print(str1)
print(str2)

print(str1 == str2)
print(str1 is str2)

kishan
chetan
False
False


In [23]:
str3 = 'chetan'
str4 = str3

print(str3 == str4)
print(str3 is str4)

True
True


In [24]:
str4 = 'kishan'

print(str3)
print(str4)

print(str3 == str4)
print(str3 is str4)

chetan
kishan
False
False


# -----------------------------------------------

In [36]:
a = ['a', 'b', 'c', 'd']
b = a

print(a)
a[2] = ['x', 'y', 'z']
print('------------------')
print(a)
print(b)

['a', 'b', 'c', 'd']
------------------
['a', 'b', ['x', 'y', 'z'], 'd']
['a', 'b', ['x', 'y', 'z'], 'd']
