# Numpy package related study points 

# List of Command statements

# ----------------------------------------------------------------

In [2]:
import numpy as np
from numpy.random import randn as rn
from numpy.random import randint as ri

# Creating Array

In [31]:
arr = np.array(['CT', 1, 2, 3]) #creating Array by LIST
arr1 = np.array(('CT', 1, 2, 3)) #creating Array by TUPLE
lst = ['CT', 1, 2, 3]
new = np.array(lst)

In [32]:
print(arr)
print(arr1)
print(lst)
print(new)

['CT' '1' '2' '3']
['CT' '1' '2' '3']
['CT', 1, 2, 3]
['CT' '1' '2' '3']


In [33]:
print(type(arr))
print(type(arr1))
print(type(lst))
print(type(new))

<type 'numpy.ndarray'>
<type 'numpy.ndarray'>
<type 'list'>
<type 'numpy.ndarray'>


In [25]:
arr = np.array([1,2,3]) #All elements converted in integer
print(arr)
print(type(arr))
print(arr.dtype)
print("----------------")
brr = np.array([1,2,3.0])  #All elements converted in float
print(brr)
print(type(brr))
print(brr.dtype)
print("----------------")
crr = np.array(['a','b','c']) #All elements converted in string
print(crr)
print(type(crr))
print(crr.dtype)
print("----------------")
drr = np.array([1,2.0,'a'])  #All elements converted in string
print(drr)
print(type(drr))
print(drr.dtype)

[1 2 3]
<type 'numpy.ndarray'>
int32
----------------
[1. 2. 3.]
<type 'numpy.ndarray'>
float64
----------------
['a' 'b' 'c']
<type 'numpy.ndarray'>
|S1
----------------
['1' '2.0' 'a']
<type 'numpy.ndarray'>
|S32


# Array shape

In [5]:
arr.shape #Return single Dimension OR 1D array

(4L,)

In [6]:
lst.shape #It gives an error

AttributeError: 'list' object has no attribute 'shape'

In [7]:
new.shape #Return single Dimension OR 1D array

(4L,)

In [16]:
#Multi-Dimension array

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2],[3,4],[5,6]])
print(arr1.shape)
print(arr2.shape)

(2L, 3L)
(3L, 2L)


In [18]:
print(arr1)
print('------------')
print(arr2)

[[1 2 3]
 [4 5 6]]
------------
[[1 2]
 [3 4]
 [5 6]]


# Reshape Array

In [22]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a.shape)
print('-------------')
print(a)

(4L, 3L)
-------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [44]:
#Reshape a into 2D array 
print('------------------------')
print('Reshape a into 2D array')
print('------------------------')
print(a.reshape(3,4))
print('-----------------')
print(a.reshape(2,6))
print('-----------------')
print(a.reshape(6,2))
print('-----------------')
print(a.reshape(1,12))
print('-----------------')
print(a.reshape(12,1))

#Reshape a into 3D array 
print('\n------------------------')
print('Reshape a into 3D array')
print('------------------------')
print(a.reshape(4,3,1))
print('-----------------')
print(a.reshape(3,1,4))
print('-----------------')
print(a.reshape(1,3,4))
print('-----------------')
print(a.reshape(2,3,2))

#Reshape a into 4D array 
print('\n------------------------')
print('Reshape a into 4D array')
print('------------------------')
print(a.reshape(1,2,3,2))
print('-----------------')
print(a.reshape(3,2,1,2))


------------------------
Reshape a into 2D array
------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
-----------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
-----------------
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
-----------------
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]

------------------------
Reshape a into 3D array
------------------------
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]
-----------------
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
-----------------
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
-----------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

------------------------
Reshape a into 4D array
------------------------
[[[[ 1  2]
   [ 3  4]
   [ 5  6]]

  [[ 7  8]
   [ 9 10]
   [11 12]]]]
-----------------
[[[[ 1  2]]

  [[ 3  4]]]


 [[[ 5  6]]

  [

In [45]:
print(a.shape)
print('--------')
print(a)

(4L, 3L)
--------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


===================================================================

In [67]:
a = np.arange(1,25,1)
type(a)

numpy.ndarray

In [68]:
print(a.shape)
a

(24L,)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [70]:
print(a.reshape(1,2,3,4))
print('------------------------')
print(a.reshape(2,1,3,4))
print('------------------------')
print(a.reshape(4,3,1,2))

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]]
------------------------
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]


 [[[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]]
------------------------
[[[[ 1  2]]

  [[ 3  4]]

  [[ 5  6]]]


 [[[ 7  8]]

  [[ 9 10]]

  [[11 12]]]


 [[[13 14]]

  [[15 16]]

  [[17 18]]]


 [[[19 20]]

  [[21 22]]

  [[23 24]]]]


In [71]:
print(a.shape)
a

(24L,)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

# transfer list to array and fetching data elements

In [2]:
lst = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
arr = np.array(lst)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
print(arr[0])
print('-------------')
print(arr[2][1])
print('-------------')
print(arr[3,1]) 
print('-------------')
print(arr[1:3])
print('-------------')
print(arr[1:3,0:2])
print('-------------')
print(arr[1:3,1:])
print('-------------')
print(arr[1:3,[0,2]])
print('-------------')
print(arr[[0,-1],[0,-1]])
print('-------------')
arr[[[0],[-1]],[0,-1]]

[1 2 3]
-------------
8
-------------
11
-------------
[[4 5 6]
 [7 8 9]]
-------------
[[4 5]
 [7 8]]
-------------
[[5 6]
 [8 9]]
-------------
[[4 6]
 [7 9]]
-------------
[ 1 12]
-------------


array([[ 1,  3],
       [10, 12]])

In [38]:
arr[[[0],[-1]],[0,-1]]

array([[ 1,  3],
       [10, 12]])

In [3]:
krr = np.arange(1,26,1).reshape(5,5)
krr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
print(krr[[0,-1]])
krr[[0,-1],[[0],[-1]]]

[[ 1  2  3  4  5]
 [21 22 23 24 25]]


array([[ 1, 21],
       [ 5, 25]])

In [5]:
print(krr[[[0],[-1]]])
print(krr[[[0],[-1]],[0,-1]])

[5]
[[ 1  5]
 [21 25]]


C:\Users\OMKARA\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


# Creating Matrix

In [6]:
np.mat([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [7]:
np.array(np.mat([1,2,3,4]))

array([[1, 2, 3, 4]])

In [8]:
issubclass(np.matrix,np.ndarray)

True

# numpy.fromfunction

np.fromfunction(): used to create array by executing a function over each coordinates.....

In [22]:
lam1 = lambda a,b:a==b #return boolean value
lam2 = lambda a,b:a-1  #return integer value
lam3 = lambda a,b:a+b  #return integer value
lam4 = lambda a,b:a*b  #return integer value

In [23]:
print(lam1(8,9))
print(lam1(4,4))
print(lam2(3,6))

False
True
2


In [24]:
np.fromfunction(lam1, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [25]:
np.fromfunction(lam1, (3,5), dtype=int)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [26]:
print(np.fromfunction(lam2, (3,5)))
print('--------------------')
print(np.fromfunction(lam2, (3,5), dtype=int))

[[-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]]
--------------------
[[-1 -1 -1 -1 -1]
 [ 0  0  0  0  0]
 [ 1  1  1  1  1]]


In [27]:
np.fromfunction(lam3, (3,5), dtype=int)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [29]:
print(np.fromfunction(lam4, (3,5)))
print('----------------------')
print(np.fromfunction(lam4, (3,5), dtype=int))

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]
----------------------
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


# np.array() AND np.asarray()

In [14]:
a = np.array([11, 22, 33, 44])

print(np.asarray(a) is a) #Creating Shallow Copy
print(np.array(a) is a)   #Creating Deeep Copy

True
False


In [12]:
a = np.array([1,2,3,4])
b = np.asarray(a)

print(a)
print(b)
print(a is b)
print('@@@@@@@@@@@@@@@@')

print("\nCHANGE SUB ELEMENTS OF MUTABLE OBJECT")
print('-------------------------------------')
b[2] = 88
print(a)
print(b)
print(a is b)
print('&&&&&&&&&&&&&&&&7')

a[0] = 999
print(a)
print(b)
print(a is b)
print('$$$$$$$$$$$$$$$$')

print("\nCHANGE WHOLE MUTABLE OBJECT")
print('-------------------------------------')
b = [0,0,0,0]
print(a)
print(b)
print( a is b)
print('%%%%%%%%%%%%%%%%%')

a[0] = 111
print(a)
print(b)
print(a is b)

[1 2 3 4]
[1 2 3 4]
True
True
@@@@@@@@@@@@@@@@

CHANGE SUB ELEMENTS OF MUTABLE OBJECT
-------------------------------------
[ 1  2 88  4]
[ 1  2 88  4]
True
&&&&&&&&&&&&&&&&7
[999   2  88   4]
[999   2  88   4]
True
$$$$$$$$$$$$$$$$

CHANGE WHOLE MUTABLE OBJECT
-------------------------------------
[999   2  88   4]
[0, 0, 0, 0]
False
%%%%%%%%%%%%%%%%%
[111   2  88   4]
[0, 0, 0, 0]
False


In [11]:
lst1 = np.array([5,6,7,8])
lst2 = np.asarray([5,6,7,8])

print(lst1)
print(lst2)
print(lst1 is lst2)

[5 6 7 8]
[5 6 7 8]
False


In [15]:
a = np.matrix([[1,2]])
np.asanyarray(a)

matrix([[1, 2]])

In [17]:
print(np.asarray(a) is a)
print(np.asanyarray(a) is a)

False
True


# data types

In [8]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [6]:
np.array([1,2,3,4]).dtype

dtype('int32')

In [3]:
import numpy as np
lst = [[1,2,3], [4,5,6], [7,8,9]]
mat = np.array(lst)
print("Here is the matrix: \n------------------\n")
print(mat)
print("\n------------------")

print("Type/Class of this object = ",type(mat))
print("Data type of this matrix = ", mat.dtype)
print("Dimension of this matrix = ", mat.ndim)
print("Shape of this matrix = ", mat.shape)
print("Size of this matrix = ", mat.size)

Here is the matrix: 
------------------

[[1 2 3]
 [4 5 6]
 [7 8 9]]

------------------
('Type/Class of this object = ', <type 'numpy.ndarray'>)
('Data type of this matrix = ', dtype('int32'))
('Dimension of this matrix = ', 2)
('Shape of this matrix = ', (3L, 3L))
('Size of this matrix = ', 9)


In [40]:
a=10

In [41]:
type(a)

int

# arange() 

In [10]:
np.arange() #Without an argument, it gives an error

TypeError: Required argument 'start' (pos 1) not found

In [9]:
np.arange(5) #One argument

array([0, 1, 2, 3, 4])

In [8]:
np.arange(0, 10) #Two arguments

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0, 10, 2) #Three arguments

array([0, 2, 4, 6, 8])

In [3]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [12]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [13]:
np.arange(10, 0, -3)

array([10,  7,  4,  1])

In [7]:
np.arange(10, 0, -1).reshape(5,2)

array([[10,  9],
       [ 8,  7],
       [ 6,  5],
       [ 4,  3],
       [ 2,  1]])

In [15]:
#Difference between range() and arange()
print(range(1,10))
print(type(range(1,10)))
print("--------------------------")
print(np.arange(1,10))
print(type(np.arange(1,10)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
<type 'list'>
--------------------------
[1 2 3 4 5 6 7 8 9]
<type 'numpy.ndarray'>


# linspace()

In [15]:
np.linspace(10) #One argument give an error 

TypeError: linspace() takes at least 2 arguments (1 given)

In [17]:
np.linspace(0, 10) #By default num=50(3rd parameter)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [21]:
print(np.linspace(0,10,5))
print(np.linspace(0,10,5, endpoint=False))

[ 0.   2.5  5.   7.5 10. ]
[0. 2. 4. 6. 8.]


In [8]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [9]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [18]:
print(np.linspace(1,10,4, retstep=True))
print(np.linspace(1,10,4, endpoint=True, retstep=True))
print(np.linspace(1,10,4, endpoint=False, retstep=True))

(array([ 1.,  4.,  7., 10.]), 3.0)
(array([ 1.,  4.,  7., 10.]), 3.0)
(array([1.  , 3.25, 5.5 , 7.75]), 2.25)


In [13]:
np.linspace(1,10,4,endpoint=False)

array([1.  , 3.25, 5.5 , 7.75])

In [14]:
np.linspace(1,10,4,endpoint=True)

array([ 1.,  4.,  7., 10.])

# np.zeros()....np.ones()....np.eye()

In [18]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.zeros(((2,5,3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
np.ones(4)

array([1., 1., 1., 1.])

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.ones(((2,4,3)))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [8]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [11]:
print(np.zeros((2,4)))
print(np.ones((4,2)))
print(np.eye(5,5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# np.logspace()

In [52]:
print(np.logspace(1.4914, 1, num=1)) #Antilog of .49 in 1 and difference 4
print(np.logspace(1.4914, 15, num=1))
print(np.logspace(1.4914, 23, num=1))

[31.00273442]
[31.00273442]
[31.00273442]


In [49]:
print(np.linspace(0,1,5, retstep=True))
print(np.logspace(0,1,5)) #Antilog

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)
[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


In [54]:
print(np.logspace(1.302,1,1))

[20.04472027]


In [61]:
print(np.linspace(1,5,5,retstep=True))
print(np.logspace(1,5,5, base=2))

(array([1., 2., 3., 4., 5.]), 1.0)
[ 2.  4.  8. 16. 32.]


# np.diag()....or....diagonal()

In [5]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
x.diagonal()

array([ 0,  5, 10, 15])

In [7]:
np.diag(x)

array([ 0,  5, 10, 15])

In [15]:
print(np.diag(x)) #Default k=0
print("------------------------")
print(np.diag(x, k=0))
print(np.diag(x, k=1))
print(np.diag(x, k=2))
print(np.diag(x, k=3))
print("------------------------")
print(np.diag(x, k=0))
print(np.diag(x, k=-1))
print(np.diag(x, k=-2))
print(np.diag(x, k=-3))

[ 0  5 10 15]
------------------------
[ 0  5 10 15]
[ 1  6 11]
[2 7]
[3]
------------------------
[ 0  5 10 15]
[ 4  9 14]
[ 8 13]
[12]


In [18]:
print(np.diag(x))
print("---------------")
print(np.diag(np.diag(x)))

[ 0  5 10 15]
---------------
[[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0 10  0]
 [ 0  0  0 15]]


# np.diagflat()

In [19]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
np.diagflat([1,2]) #Default k=0

array([[1, 0],
       [0, 2]])

In [21]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [22]:
np.diagflat([1,2], 3)

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
print(np.diagflat([1,2], -0))
print("--------------------")
print(np.diagflat([1,2], -1))
print("--------------------")
print(np.diagflat([1,2], -2))
print("--------------------")
print(np.diagflat([1,2], -3))

[[1 0]
 [0 2]]
--------------------
[[0 0 0]
 [1 0 0]
 [0 2 0]]
--------------------
[[0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]]
--------------------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]]


# np.tri().......create triangle shape with 1, remaining are 0

In [26]:
np.tri(3,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [27]:
np.tri(3,5, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [28]:
np.tri(3,5, k=1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [29]:
np.tri(3,5, 2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [30]:
np.tri(3,5, k=4, dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.tri(3,5, k=-1, dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0]])

In [32]:
np.tri(3,5, k=-2, dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [34]:
np.tri(3,5, k=-3, dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Random number generation
rand().....and.....randn()

In [36]:
#Range 0,1
np.random.rand(3,3)

array([[0.91699409, 0.40213448, 0.65921398],
       [0.3022398 , 0.26578028, 0.89219532],
       [0.59375224, 0.77376875, 0.73714987]])

In [40]:
## Standard normal distribution 
np.random.randn(3,3)

array([[-0.31456627,  1.10041788,  0.32106775],
       [-0.3544325 ,  0.39199723,  0.01650092],
       [ 0.2231155 ,  0.2308087 , -0.57000355]])

# randint().....creates random number between given range

In [45]:
np.random.randint(1,9) #Generate random number between 1 and 9

7

In [47]:
np.random.randint(1,9,3) #Generate random numbers between 1 and 9 

array([2, 7, 6])

In [48]:
np.random.randint(1,100,10)

array([66, 63, 43, 45, 57, 97, 36, 54, 12, 66])

# Reshaping

In [50]:
a = ri(1,100,30)
a

array([13, 16, 57, 12, 84, 28, 60, 85, 28, 17, 88, 79, 26, 69,  7, 24, 36,
       86, 41, 93, 70, 28, 13, 94, 57, 14, 88, 56, 28, 91])

In [52]:
b = a.reshape(2,3,5)
b

array([[[13, 16, 57, 12, 84],
        [28, 60, 85, 28, 17],
        [88, 79, 26, 69,  7]],

       [[24, 36, 86, 41, 93],
        [70, 28, 13, 94, 57],
        [14, 88, 56, 28, 91]]])

In [55]:
c = a.reshape(6,-19876) 
#Automatic -19876 taken as 5, because 6X5=30
c

array([[13, 16, 57, 12, 84],
       [28, 60, 85, 28, 17],
       [88, 79, 26, 69,  7],
       [24, 36, 86, 41, 93],
       [70, 28, 13, 94, 57],
       [14, 88, 56, 28, 91]])

In [58]:
d = a.reshape(-2,3)
#Automatic -2 taken as 10, because 10X3=30
d

array([[13, 16, 57],
       [12, 84, 28],
       [60, 85, 28],
       [17, 88, 79],
       [26, 69,  7],
       [24, 36, 86],
       [41, 93, 70],
       [28, 13, 94],
       [57, 14, 88],
       [56, 28, 91]])

# np.sort()

In [72]:
a = np.random.randint(1,100,15)
print(a)
print("-------------------------------------------------")
print(np.sort(a))
print(np.max(a))
print(np.argmax(a)) #Return index of max value

[73 69 53 92 51 97 40 69 86 37 39 77 59 68  5]
-------------------------------------------------
[ 5 37 39 40 51 53 59 68 69 69 73 77 86 92 97]
97
5


In [74]:
a = np.random.randint(1,100,15).reshape(5,3)
a

array([[80, 76, 76],
       [68, 39, 68],
       [58, 94,  6],
       [91, 67, 43],
       [ 6, 20, 35]])

In [78]:
print(np.max(a))
print(np.max(a, axis=1)) #ROW wise maximum values
print(np.max(a, axis=0)) #COLUMN wise maximum values

94
[80 68 94 91 35]
[91 94 76]


# indexing

In [3]:
a = np.random.randint(1,100,30).reshape(5,6)
a

array([[90, 99, 49, 30, 40, 97],
       [69, 15,  3, 57, 94, 32],
       [48, 59, 81, 68, 48, 96],
       [47, 34, 73, 89, 42, 75],
       [34, 63, 89,  7, 68, 40]])

In [7]:
a[[[2],[3]],[2,3]]

array([[81, 68],
       [73, 89]])

In [8]:
a+2

array([[ 92, 101,  51,  32,  42,  99],
       [ 71,  17,   5,  59,  96,  34],
       [ 50,  61,  83,  70,  50,  98],
       [ 49,  36,  75,  91,  44,  77],
       [ 36,  65,  91,   9,  70,  42]])

In [9]:
a*2

array([[180, 198,  98,  60,  80, 194],
       [138,  30,   6, 114, 188,  64],
       [ 96, 118, 162, 136,  96, 192],
       [ 94,  68, 146, 178,  84, 150],
       [ 68, 126, 178,  14, 136,  80]])

In [94]:
a = np.random.randint(1,10,9).reshape(3,3)
b = np.random.randint(1,10,9).reshape(3,3)

print(a)
print(b)

[[4 8 8]
 [5 4 6]
 [6 6 9]]
[[6 8 7]
 [5 5 9]
 [4 3 5]]


In [95]:
a*b

array([[24, 64, 56],
       [25, 20, 54],
       [24, 18, 45]])

In [101]:
a/b

array([[0, 1, 1],
       [1, 0, 0],
       [1, 2, 1]])

# Broadcasting

In [120]:
a = np.random.randint(1,100,20)
a

array([40, 70, 98, 19, 16, 11, 45, 45, 38, 32, 20, 74, 81, 79, 62, 16, 57,
       25, 15, 36])

In [121]:
a[5]

11

In [122]:
a[5:9] = 100
a

array([ 40,  70,  98,  19,  16, 100, 100, 100, 100,  32,  20,  74,  81,
        79,  62,  16,  57,  25,  15,  36])

In [123]:
a[5:] = 100
a

array([ 40,  70,  98,  19,  16, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

# Array Math

In [ ]:
#All array math functions like
#np.sqrt()
#np.exp()
#np.log()
#np.fmod()  etc.......

In [125]:
a = np.random.randint(1,10,9).reshape(3,3)
b = np.random.randint(1,10,9).reshape(3,3)

print(a)
print("-------------")
print(b)

[[9 2 3]
 [7 3 2]
 [3 2 6]]
-------------
[[4 3 3]
 [6 7 3]
 [4 1 7]]


In [126]:
np.fmod(a,b) #Return remainder of the division

array([[1, 2, 0],
       [1, 3, 2],
       [3, 0, 6]])

# Subseting

In [127]:
a = np.sort(np.random.randint(10,100,20))
a

array([12, 26, 37, 41, 43, 48, 51, 51, 51, 52, 54, 61, 61, 61, 64, 65, 70,
       70, 87, 90])

In [129]:
a>60

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [130]:
a[a>60] #Subseting

array([61, 61, 61, 64, 65, 70, 70, 87, 90])