In [17]:
import numpy as np
import pandas as pd
from numpy.random import randn as rn

# List of command statements

In [2]:
#url = "https://raw.githubusercontent.com//datasciencedojo/datasets/master/titanic.csv"
url = "All_data_files/titanic.csv"
data = pd.read_csv(url, sep=',')

In [3]:
 data.iloc[np.where(data['Fare']==max(data['Fare']))]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C

# Generated random numbers in matrix

In [4]:
matrix_data = rn(4, 3)
matrix_data

array([[ 1.52225215,  0.43403252,  1.66472867],
       [-0.80834975,  0.10252548, -0.7311078 ],
       [-0.2951118 ,  0.44181579,  1.70956077],
       [ 0.53003126, -1.04863071, -1.22450296]])

In [3]:
# Every time random data not changed
np.random.seed(1)
# ----------------------------------
matrix_data = rn(4, 3)
matrix_data

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ,  0.3190391 ],
       [-0.24937038,  1.46210794, -2.06014071]])

In [4]:
np.random.seed(1)
matrix_data = rn(6, 4)
row_lbl = [12, 23, 34, 45, 56, 56]
col_lbl = ['W', 'X', 'Y', 'Z']
df = pd.DataFrame(matrix_data, row_lbl, col_lbl)
df

W         X         Y         Z
12  1.624345 -0.611756 -0.528172 -1.072969
23  0.865408 -2.301539  1.744812 -0.761207
34  0.319039 -0.249370  1.462108 -2.060141
45 -0.322417 -0.384054  1.133769 -1.099891
56 -0.172428 -0.877858  0.042214  0.582815
56 -1.100619  1.144724  0.901591  0.502494

# loc[ ] takes User Given Name indexes (point to location)
# iloc[ ] takes system default indexes (point to integer location)
# ix[ ] is combination of loc and iloc, and it will remove from python

In [5]:
df>0

W      X      Y      Z
12   True  False  False  False
23   True  False   True  False
34   True  False   True  False
45  False  False   True  False
56  False  False   True   True
56  False   True   True   True

In [6]:
df[df>0]

W         X         Y         Z
12  1.624345       NaN       NaN       NaN
23  0.865408       NaN  1.744812       NaN
34  0.319039       NaN  1.462108       NaN
45       NaN       NaN  1.133769       NaN
56       NaN       NaN  0.042214  0.582815
56       NaN  1.144724  0.901591  0.502494

In [16]:
df.loc[[12, 43, 45]]

C:\Users\OMKARA\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


W         X         Y         Z
12  1.624345 -0.611756 -0.528172 -1.072969
43       NaN       NaN       NaN       NaN
45 -0.322417 -0.384054  1.133769 -1.099891

In [12]:
df.loc[[12,34,45]]>0

W      X      Y      Z
12   True  False  False  False
34   True  False   True  False
45  False  False   True  False

In [10]:
df[df.loc[[12,34,45]]>0]

W   X         Y   Z
12  1.624345 NaN       NaN NaN
23       NaN NaN       NaN NaN
34  0.319039 NaN  1.462108 NaN
45       NaN NaN  1.133769 NaN
56       NaN NaN       NaN NaN
56       NaN NaN       NaN NaN

In [11]:
df.loc[34]

W    0.319039
X   -0.249370
Y    1.462108
Z   -2.060141
Name: 34, dtype: float64

In [12]:
df.loc[56]

W         X         Y         Z
56 -0.172428 -0.877858  0.042214  0.582815
56 -1.100619  1.144724  0.901591  0.502494

In [13]:
df.iloc[2]

W    0.319039
X   -0.249370
Y    1.462108
Z   -2.060141
Name: 34, dtype: float64

In [14]:
df

W         X         Y         Z
12  1.624345 -0.611756 -0.528172 -1.072969
23  0.865408 -2.301539  1.744812 -0.761207
34  0.319039 -0.249370  1.462108 -2.060141
45 -0.322417 -0.384054  1.133769 -1.099891
56 -0.172428 -0.877858  0.042214  0.582815
56 -1.100619  1.144724  0.901591  0.502494

In [15]:
df.loc[[23,56]]

W         X         Y         Z
23  0.865408 -2.301539  1.744812 -0.761207
56 -0.172428 -0.877858  0.042214  0.582815
56 -1.100619  1.144724  0.901591  0.502494

In [16]:
df.loc[[23,56],]

W         X         Y         Z
23  0.865408 -2.301539  1.744812 -0.761207
56 -0.172428 -0.877858  0.042214  0.582815
56 -1.100619  1.144724  0.901591  0.502494

In [17]:
df.loc[[23,56],['X','Z']]

X         Z
23 -2.301539 -0.761207
56 -0.877858  0.582815
56  1.144724  0.502494

In [18]:
df.loc[23:56, 'X':'Z']

X         Y         Z
23 -2.301539  1.744812 -0.761207
34 -0.249370  1.462108 -2.060141
45 -0.384054  1.133769 -1.099891
56 -0.877858  0.042214  0.582815
56  1.144724  0.901591  0.502494

In [19]:
df.iloc[[1,4]]

W         X         Y         Z
23  0.865408 -2.301539  1.744812 -0.761207
56 -0.172428 -0.877858  0.042214  0.582815

In [20]:
 df.iloc[1:4]

W         X         Y         Z
23  0.865408 -2.301539  1.744812 -0.761207
34  0.319039 -0.249370  1.462108 -2.060141
45 -0.322417 -0.384054  1.133769 -1.099891

In [21]:
df.iloc[[4,1,2],[1,3]]

X         Z
56 -0.877858  0.582815
23 -2.301539 -0.761207
34 -0.249370 -2.060141

In [22]:
df

W         X         Y         Z
12  1.624345 -0.611756 -0.528172 -1.072969
23  0.865408 -2.301539  1.744812 -0.761207
34  0.319039 -0.249370  1.462108 -2.060141
45 -0.322417 -0.384054  1.133769 -1.099891
56 -0.172428 -0.877858  0.042214  0.582815
56 -1.100619  1.144724  0.901591  0.502494

In [23]:
df.iloc[-1]

W   -1.100619
X    1.144724
Y    0.901591
Z    0.502494
Name: 56, dtype: float64

In [24]:
df.iloc[[0,4],[0,3]]

W         Z
12  1.624345 -1.072969
56 -0.172428  0.582815

In [25]:
df.iloc[[0,-2],[0,-1]]

W         Z
12  1.624345 -1.072969
56 -0.172428  0.582815

In [26]:
df.iloc[[-6,-2],[-4,-1]]

W         Z
12  1.624345 -1.072969
56 -0.172428  0.582815

In [27]:
df.iloc[1:4]

W         X         Y         Z
23  0.865408 -2.301539  1.744812 -0.761207
34  0.319039 -0.249370  1.462108 -2.060141
45 -0.322417 -0.384054  1.133769 -1.099891

In [28]:
#-----------------------------------
df.iloc[1:4,0:3]

W         X         Y
23  0.865408 -2.301539  1.744812
34  0.319039 -0.249370  1.462108
45 -0.322417 -0.384054  1.133769

In [29]:
df.loc[23:45, 'W':'Y']

W         X         Y
23  0.865408 -2.301539  1.744812
34  0.319039 -0.249370  1.462108
45 -0.322417 -0.384054  1.133769

In [30]:
df.iloc[-5:-2, -4:-1]

W         X         Y
23  0.865408 -2.301539  1.744812
34  0.319039 -0.249370  1.462108
45 -0.322417 -0.384054  1.133769

In [31]:
# In future ix[] will no be available, So every time ix[] shows a warning
# ix[] is combination of loc[] and iloc[]
# So, it is suggested to use loc[], & iloc[] rather than ix[]
# if you install new python, it may be possible that ix[] will be removed from python latest version


df.ix[[12]]

C:\Users\OMKARA\Anaconda2\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  import sys


W         X         Y         Z
12  1.624345 -0.611756 -0.528172 -1.072969

In [32]:
df.ix[56]

C:\Users\OMKARA\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


W         X         Y         Z
56 -0.172428 -0.877858  0.042214  0.582815
56 -1.100619  1.144724  0.901591  0.502494

In [33]:
df.ix[56,'X']

C:\Users\OMKARA\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


56   -0.877858
56    1.144724
Name: X, dtype: float64

In [34]:
df.ix[1:3, 1:3]

C:\Users\OMKARA\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Empty DataFrame
Columns: [X, Y]
Index: []

# Add new Column

In [35]:
#------------------------------------
print("A new colummn created b assigning it in relation to existing columns\n")
df['new_X+Y'] = df['X'] + df['Y']
df['new_X-Y'] = df['X'] - df['Y']
df['Extra'] = "AB BC CD EF FG GH".split()
df

A new colummn created b assigning it in relation to existing columns



W         X         Y         Z   new_X+Y   new_X-Y Extra
12  1.624345 -0.611756 -0.528172 -1.072969 -1.139928 -0.083585    AB
23  0.865408 -2.301539  1.744812 -0.761207 -0.556727 -4.046350    BC
34  0.319039 -0.249370  1.462108 -2.060141  1.212738 -1.711478    CD
45 -0.322417 -0.384054  1.133769 -1.099891  0.749715 -1.517824    EF
56 -0.172428 -0.877858  0.042214  0.582815 -0.835645 -0.920072    FG
56 -1.100619  1.144724  0.901591  0.502494  2.046314  0.243133    GH

In [36]:
df

W         X         Y         Z   new_X+Y   new_X-Y Extra
12  1.624345 -0.611756 -0.528172 -1.072969 -1.139928 -0.083585    AB
23  0.865408 -2.301539  1.744812 -0.761207 -0.556727 -4.046350    BC
34  0.319039 -0.249370  1.462108 -2.060141  1.212738 -1.711478    CD
45 -0.322417 -0.384054  1.133769 -1.099891  0.749715 -1.517824    EF
56 -0.172428 -0.877858  0.042214  0.582815 -0.835645 -0.920072    FG
56 -1.100619  1.144724  0.901591  0.502494  2.046314  0.243133    GH

In [37]:
np.round(df.iloc[0,1]-df.iloc[0,2], 6)

-0.083585

# Drop columns and rows

In [38]:
df

W         X         Y         Z   new_X+Y   new_X-Y Extra
12  1.624345 -0.611756 -0.528172 -1.072969 -1.139928 -0.083585    AB
23  0.865408 -2.301539  1.744812 -0.761207 -0.556727 -4.046350    BC
34  0.319039 -0.249370  1.462108 -2.060141  1.212738 -1.711478    CD
45 -0.322417 -0.384054  1.133769 -1.099891  0.749715 -1.517824    EF
56 -0.172428 -0.877858  0.042214  0.582815 -0.835645 -0.920072    FG
56 -1.100619  1.144724  0.901591  0.502494  2.046314  0.243133    GH

In [39]:
# Deletion of "Extra" column temporarily
#df.drop('Extra', axis=1) 
# OR
df.drop('Extra', 1) #Because axis is 2nd position argument

W         X         Y         Z   new_X+Y   new_X-Y
12  1.624345 -0.611756 -0.528172 -1.072969 -1.139928 -0.083585
23  0.865408 -2.301539  1.744812 -0.761207 -0.556727 -4.046350
34  0.319039 -0.249370  1.462108 -2.060141  1.212738 -1.711478
45 -0.322417 -0.384054  1.133769 -1.099891  0.749715 -1.517824
56 -0.172428 -0.877858  0.042214  0.582815 -0.835645 -0.920072
56 -1.100619  1.144724  0.901591  0.502494  2.046314  0.243133

In [40]:
# Temporarily deleted column now available
df.drop()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [41]:
# Deletion of "Extra" column permanently
df.drop('Extra', axis=1, inplace=True)
df

W         X         Y         Z   new_X+Y   new_X-Y
12  1.624345 -0.611756 -0.528172 -1.072969 -1.139928 -0.083585
23  0.865408 -2.301539  1.744812 -0.761207 -0.556727 -4.046350
34  0.319039 -0.249370  1.462108 -2.060141  1.212738 -1.711478
45 -0.322417 -0.384054  1.133769 -1.099891  0.749715 -1.517824
56 -0.172428 -0.877858  0.042214  0.582815 -0.835645 -0.920072
56 -1.100619  1.144724  0.901591  0.502494  2.046314  0.243133

In [42]:
# Permanently deleted olumn now NOT available
df

W         X         Y         Z   new_X+Y   new_X-Y
12  1.624345 -0.611756 -0.528172 -1.072969 -1.139928 -0.083585
23  0.865408 -2.301539  1.744812 -0.761207 -0.556727 -4.046350
34  0.319039 -0.249370  1.462108 -2.060141  1.212738 -1.711478
45 -0.322417 -0.384054  1.133769 -1.099891  0.749715 -1.517824
56 -0.172428 -0.877858  0.042214  0.582815 -0.835645 -0.920072
56 -1.100619  1.144724  0.901591  0.502494  2.046314  0.243133

In [43]:
# Deletion of given indexed row temoratily
#df.drop(23, axis=0) # default value of axis=0, if axis=0 not mentioned, then it is also valid.
# OR
df.drop(23)

W         X         Y         Z   new_X+Y   new_X-Y
12  1.624345 -0.611756 -0.528172 -1.072969 -1.139928 -0.083585
34  0.319039 -0.249370  1.462108 -2.060141  1.212738 -1.711478
45 -0.322417 -0.384054  1.133769 -1.099891  0.749715 -1.517824
56 -0.172428 -0.877858  0.042214  0.582815 -0.835645 -0.920072
56 -1.100619  1.144724  0.901591  0.502494  2.046314  0.243133

In [44]:
# Temporarily deleted row now available
df

W         X         Y         Z   new_X+Y   new_X-Y
12  1.624345 -0.611756 -0.528172 -1.072969 -1.139928 -0.083585
23  0.865408 -2.301539  1.744812 -0.761207 -0.556727 -4.046350
34  0.319039 -0.249370  1.462108 -2.060141  1.212738 -1.711478
45 -0.322417 -0.384054  1.133769 -1.099891  0.749715 -1.517824
56 -0.172428 -0.877858  0.042214  0.582815 -0.835645 -0.920072
56 -1.100619  1.144724  0.901591  0.502494  2.046314  0.243133

In [45]:
df.drop(23, inplace=True)
# OR
#df = df.drop(23)

In [9]:
# drop duplicate records from given column name
temp = pd.read_csv('All_data_files/duplicate.csv')

In [10]:
temp

name surename  age
0   ct    patel   90
1   kt    patel   23
2   dt      gor   12
3   jd      doo   78
4   kt      gor   87
5   ct       kk   66

In [5]:
# drop all duplicate records from name column except first record
# default drop_duplicates(keep='first')
temp.drop_duplicates('name')
#temp.drop_duplicates('name', inplace=True)

name surename  age
0   ct    patel   90
1   kt    patel   23
2   dt      gor   12
3   jd      doo   78

In [7]:
# drop all duplicate records from name column except last record
#temp.drop_duplicates('name', keep='last')
temp.drop_duplicates('name', keep='last', inplace=True)

In [ ]:
# drop all duplicate records with first & last records.
temp.drop_duplicates('name', keep=False)

In [46]:
# Permanently deleted olumn now NOT available
df

W         X         Y         Z   new_X+Y   new_X-Y
12  1.624345 -0.611756 -0.528172 -1.072969 -1.139928 -0.083585
34  0.319039 -0.249370  1.462108 -2.060141  1.212738 -1.711478
45 -0.322417 -0.384054  1.133769 -1.099891  0.749715 -1.517824
56 -0.172428 -0.877858  0.042214  0.582815 -0.835645 -0.920072
56 -1.100619  1.144724  0.901591  0.502494  2.046314  0.243133

# Creting MATRIX

In [47]:
# We can not drop/delete specific data from dataframe
# But, We can replace specific data with NULL value.  

# We can only drop/delete whole column or whole row 

In [48]:
# matrix() of numpy package is used to create matrix of numbers, string
# There are 3-Ways to create matrix.
# WAY-1: Columns are separated by (,)COMMAS, & Rows are separated by (;)semi-colons. 
#         (In this way, metrix elements are treated as string so elements are written inside ""/'')
# WAY-2: Columns are separated by ( )SPACES, & Rows are separated by (;)semi-colons.
#         (In this way, metrix elements are treated as string so elements are written inside ""/'')
# WAY-3: Columns are separated by [] LIST, Rows are separated by (,)commas.

In [49]:
# WAY-1 for number
matrix_data = np.matrix('1 2 3; 4 5 6; 7 8 9')
matrix_data

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
# WAY-2 for number
matrix_data = np.matrix('1,2,3; 4,5,6; 7,8,9')
matrix_data

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
# WAY-3 for number
matrix_data = np.matrix([[1,2,3], [4,5,6], [7,8,9]])
matrix_data

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [52]:
# WAY-1 for string
matrix_data = np.matrix("'a' 'b' 'c'; 'd' 'e' 'f'; 'g' 'h' 'i'")
matrix_data

matrix([['a', 'b', 'c'],
        ['d', 'e', 'f'],
        ['g', 'h', 'i']], dtype='|S1')

In [53]:
# WAY-2 for string
matrix_data = np.matrix("'a','b','c'; 'd','e','f'; 'g','h','i'")
matrix_data

matrix([['a', 'b', 'c'],
        ['d', 'e', 'f'],
        ['g', 'h', 'i']], dtype='|S1')

In [54]:
# WAY-3 for string
matrix_data = np.matrix([['a','b','c'], ['d','e','f'], ['g','h','i']])
matrix_data

matrix([['a', 'b', 'c'],
        ['d', 'e', 'f'],
        ['g', 'h', 'i']], dtype='|S1')

In [55]:
matrix_data = np.matrix('22,66,140; 42,70,148; 30,62,125; 35,68,160; 25,62,152')
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [56]:
row_lbl = ['A', 'B', 'C', 'D', 'E']
col_lbl = ['Age', 'Height', 'Weight']
df = pd.DataFrame(matrix_data, index=row_lbl, columns=col_lbl)
df

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

# Perform LOGICAL operations on matrix

In [57]:
df['Height']>65

A     True
B     True
C    False
D     True
E    False
Name: Height, dtype: bool

In [58]:
df[df['Height']>65]

Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [59]:
df[df['Height']==62]

Age  Height  Weight
C   30      62     125
E   25      62     152

In [60]:
df

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [61]:
# Logical OR operation performed by (|)pipe operator

df[(df['Age']>25) | (df['Weight']>140)]

Age  Height  Weight
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [62]:
# Logical AND operation performed by (&) operator

df[(df['Age']>30) & (df['Height']>62) & (df['Weight']>125)]

Age  Height  Weight
B   42      70     148
D   35      68     160

In [63]:
df[(df['Age'] >= 30) & (df['Height'] >= 62) & (df['Weight'] >= 125)]

Age  Height  Weight
B   42      70     148
C   30      62     125
D   35      68     160

# Reset index using reset_index(

In [64]:
df

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [65]:
# Temporarily Reset index WITHOUT deleting previous index 
# Old index will become new column
# Using reset_index()

df.reset_index()

index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152

In [66]:
# Temporarily reset index WITH deleting previous index 
# Temporarily, Old index will be deleted.
# Using reset_index(drop=True)

df.reset_index(drop=True)

Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152

In [67]:
# No change index, Original index again as it is

df

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [68]:
#df.reset_index(inplace=True) #Permanently reset index WITHOUT deleting previous index
df.reset_index(drop=True, inplace=True) #Permanently reset index WITH deleting previous index
df

Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152

In [69]:
# Indexes changed permanently
df

Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152

# Set index using set_index()

In [70]:
"Student Teacher Engineer Doctor Nurse".split()

['Student', 'Teacher', 'Engineer', 'Doctor', 'Nurse']

In [71]:
print("New Column Profession Added\n"+'-'*27)
df['Profession'] = "Student Teacher Engineer Doctor Nurse".split()
df

New Column Profession Added
---------------------------


Age  Height  Weight Profession
0   22      66     140    Student
1   42      70     148    Teacher
2   30      62     125   Engineer
3   35      68     160     Doctor
4   25      62     152      Nurse

In [72]:
# Temporarily, Profession column to be made as index
df.set_index('Profession')

Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152

In [73]:
# No change in previous index
df

Age  Height  Weight Profession
0   22      66     140    Student
1   42      70     148    Teacher
2   30      62     125   Engineer
3   35      68     160     Doctor
4   25      62     152      Nurse

In [74]:
# Permanently, Profession column as index
df.set_index('Profession', inplace=True)
df

Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152

In [75]:
# Permanently revious index changed
df

Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152

# Set multi indexes

When you use multi index concept, at that time, to get data from daframe, loc[ ] is more preferable than iloc[ ], and ix[ ].

In [18]:
outsie = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]
zip_lst = list(zip(outsie, inside))
zip_lst

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [19]:
multi_index = pd.MultiIndex.from_tuples(zip_lst)
multi_index

MultiIndex(levels=[[u'G1', u'G2'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [20]:
df = pd.DataFrame(np.round(rn(6,4)), index=multi_index, columns=['A','B','C','D'])
df

A    B    C    D
G1 1  1.0 -1.0  0.0 -1.0
   2  0.0  1.0 -1.0  0.0
   3 -1.0 -1.0 -1.0  0.0
G2 1 -1.0  0.0  2.0  1.0
   2  0.0 -1.0 -1.0  2.0
   3  0.0 -1.0  0.0  2.0

In [21]:
df.iloc[0]

A    1.0
B   -1.0
C    0.0
D   -1.0
Name: (G1, 1), dtype: float64

In [22]:
df.loc['G1']

A    B    C    D
1  1.0 -1.0  0.0 -1.0
2  0.0  1.0 -1.0  0.0
3 -1.0 -1.0 -1.0  0.0

In [23]:
df.ix[0]

C:\Users\OMKARA\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


A    1.0
B   -1.0
C    0.0
D   -1.0
Name: (G1, 1), dtype: float64

In [24]:
df.loc['G1'].loc[3, ['B','C']]

B   -1.0
C   -1.0
Name: 3, dtype: float64

In [25]:
df.iloc[0].iloc[2,[1,2]] #Gives Error

IndexingError: Too many indexers

In [26]:
df.loc['G2'].iloc[0,[1,2,3]]

B    0.0
C    2.0
D    1.0
Name: 1, dtype: float64

In [27]:
df.ix['G2'].iloc[1,[1,2,3]]

C:\Users\OMKARA\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


B   -1.0
C   -1.0
D    2.0
Name: 2, dtype: float64

In [28]:
df

A    B    C    D
G1 1  1.0 -1.0  0.0 -1.0
   2  0.0  1.0 -1.0  0.0
   3 -1.0 -1.0 -1.0  0.0
G2 1 -1.0  0.0  2.0  1.0
   2  0.0 -1.0 -1.0  2.0
   3  0.0 -1.0  0.0  2.0

In [111]:
l1 = ['A','A','A','A', 'B','B','B','B', 'C','C','C','C']
l2 = [1,2,3,1,2,3,1,2,3,1,2,3]
l3 = [88,99,88,99,88,99,88,99,88,99,88,99]
tp = list(zip(l1,l2,l3))
mul_tp_index = pd.MultiIndex.from_tuples(tp)
df = pd.DataFrame(np.round(rn(12,4), 2), index=mul_tp_index, columns=['W','X','Y','Z'])
df

W     X     Y     Z
A 1 88  0.45  1.10 -0.28  2.06
  2 99  1.76 -0.06 -2.41 -1.78
  3 88 -0.78  1.12  0.31 -2.09
  1 99 -0.23  1.61 -0.37 -0.75
B 2 88  2.05  0.05 -0.48  0.35
  3 99  0.02 -0.43  1.21  1.12
  1 88  0.84 -0.10  1.15 -0.05
  2 99  0.47  1.03  0.81  1.79
C 3 88  0.45 -1.68 -1.16  1.35
  1 99 -0.33  0.39 -0.85  1.00
  2 88 -0.38  1.46 -0.53  1.12
  3 99  0.67 -0.72  1.10 -0.90

In [138]:
df.loc[['B','C']]

W     X     Y     Z
B 2 88  2.05  0.05 -0.48  0.35
  3 99  0.02 -0.43  1.21  1.12
  1 88  0.84 -0.10  1.15 -0.05
  2 99  0.47  1.03  0.81  1.79
C 3 88  0.45 -1.68 -1.16  1.35
  1 99 -0.33  0.39 -0.85  1.00
  2 88 -0.38  1.46 -0.53  1.12
  3 99  0.67 -0.72  1.10 -0.90

In [131]:
df.loc['B']

W     X     Y     Z
2 88  2.05  0.05 -0.48  0.35
3 99  0.02 -0.43  1.21  1.12
1 88  0.84 -0.10  1.15 -0.05
2 99  0.47  1.03  0.81  1.79

In [141]:
df.loc['B', ['X', 'Z']]

X     Z
2 88  0.05  0.35
3 99 -0.43  1.12
1 88 -0.10 -0.05
2 99  1.03  1.79

In [142]:
df.loc['B', 'X']

C:\Users\OMKARA\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  """Entry point for launching an IPython kernel.


2  88    0.05
3  99   -0.43
1  88   -0.10
2  99    1.03
Name: X, dtype: float64

In [134]:
df.loc['B'].loc[3]

W     X     Y     Z
99  0.02 -0.43  1.21  1.12

In [135]:
df.loc['B'].loc[2]

W     X     Y     Z
88  2.05  0.05 -0.48  0.35
99  0.47  1.03  0.81  1.79

In [144]:
df.loc['B'].loc[2, 'X']

88    0.05
99    1.03
Name: X, dtype: float64

In [145]:
df.loc['B'].loc[2, ['X', 'Z']]

X     Z
88  0.05  0.35
99  1.03  1.79

In [136]:
df.loc['B'].loc[2].loc[99]

W    0.47
X    1.03
Y    0.81
Z    1.79
Name: 99, dtype: float64

In [146]:
df.loc['B'].loc[2].loc[99, 'X']

1.03

In [149]:
df.loc['B'].loc[2].loc[99, ['Y', 'Z']]

Y    0.81
Z    1.79
Name: 99, dtype: float64